<a href="https://colab.research.google.com/github/marammohamed123/tasks/blob/main/numpy%20assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#: Create a 4X2 integer array and Prints its attributes
import numpy as np
array=np.empty([4,2],dtype=np.uint16)
print("shape of array")
print(array.shape)
print("\n")
print("dimension of array")
print(array.ndim)
print("\n")
print("The Length of each element of the array")
print(array.itemsize)
print("\n")

shape of array
(4, 2)


dimension of array
2


The Length of each element of the array
2




In [2]:
#Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
import numpy as np
array=np.arange(100,200,10)
array=array.reshape(5,2)
print(array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [3]:
#Exercise 3: Following is the provided numPy array. Return array of items by taking the third column from all rows
import numpy as np
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print("\n")
new_array=sampleArray[...,2]
print(new_array)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


[33 66 99]


In [4]:
#: Return array of odd rows and even columns from below numpy array
import numpy as np
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print("\n")
new_array=sampleArray[::2,1::2]
print(new_array)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


[[ 6 12]
 [30 36]
 [54 60]]


In [5]:
'''Exercise 5: Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the 
square of each element'''
import numpy as np
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print("result array by adding the following two NumPy arrays:")
sum_array=arrayOne+arrayTwo
print(sum_array)
print("\n")
print(" the result array by calculating the square of each element")
square=sum_array**2
print(square)


result array by adding the following two NumPy arrays:
[[20 39 33]
 [25 25 28]]


 the result array by calculating the square of each element
[[ 400 1521 1089]
 [ 625  625  784]]
