<a href="https://colab.research.google.com/github/marammohamed123/tasks/blob/main/numpy%20exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1: Split the array into four equal-sized sub-arrays
import numpy as np
Array = np.arange(10, 34, 1)
Array = Array.reshape(8,3)
print (Array)
print("\nDividing 8X3 array into 4 sub array\n")
split_Arrays = np.split(Array, 4) 
print(split_Arrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [6]:
#2:Sort following NumPy array
Array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sort_Row = Array[:,Array[1,:].argsort()]
print("Sorting by row")
print(sort_Row)
print("Sorting by column")
sort_Column = Array[Array[:,1].argsort()]
print(sort_Column)

Sorting by row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting by column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [7]:
#3: Print max from axis 0 and min from axis 1 from the following 2-D array
Array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (Array)
min_One = np.amin(Array, 1) 
print("Printing amin Of Axis 1")
print(min_One)
max_One = np.amax(Array, 0) 
print("Printing amax Of Axis 0")
print(max_One)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


In [9]:
#4:Delete the second column from a given array and insert the following new column in its place
Array = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (Array)
print("Array after deleting ")
Array = np.delete(Array , 1, axis = 1) 
print (Array)

array = np.array([[10,10,10]])
print("Array after inserting ")
Array = np.insert(Array , 1, array, axis = 1) 
print (Array)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting 
[[34 73]
 [82 12]
 [53 66]]
Array after inserting 
[[34 10 73]
 [82 10 12]
 [53 10 66]]
